#!/bin/bash
# shellcheck shell=bash
# shellcheck disable=SC2016
# shellcheck disable=SC2154

# 自动更新
if [[ "${AUTO_UPDATE}" = "true" ]];then
  cd /embyExternalUrl && git pull
fi

# emby 不存在emby.conf文件，则创建软链接，存在则说明以前已经创建过软链接或者挂载该目录，无需处理
if [ "${SERVER}" = "emby" ] && [ ! -e "/etc/nginx/conf.d/emby.conf" ]; then
  # 删除原有配置文件
  rm -rf /etc/nginx/conf.d /etc/nginx/nginx.conf
  # 根据服务获取不同的配置文件
  ln -s /embyExternalUrl/emby2Alist/nginx/conf.d /etc/nginx/conf.d
  ln -s /embyExternalUrl/emby2Alist/nginx/nginx.conf /etc/nginx/nginx.conf
fi

# plex 不存在plex.conf文件，则创建软链接，存在则说明以前已经创建过软链接或者挂载该目录，无需处理
if [ "${SERVER}" = "plex" ] && [ ! -e "/etc/nginx/conf.d/plex.conf" ]; then
  # 删除原有配置文件
  rm -rf /etc/nginx/conf.d /etc/nginx/nginx.conf
  # 根据服务获取不同的配置文件
  ln -s /embyExternalUrl/plex2Alist/nginx/conf.d /etc/nginx/conf.d
  ln -s /embyExternalUrl/plex2Alist/nginx/nginx.conf /etc/nginx/nginx.conf
fi

# 替换http、https端口
sed -i "s/8091/${NGINX_PORT}/g" "/etc/nginx/conf.d/includes/http.conf"
sed -i "s/8095/${NGINX_SSL_PORT}/g" "/etc/nginx/conf.d/includes/https.conf"

# 软连接配置文件
if [ ! -h "/etc/nginx/conf.d/constant.js" ]; then
  rm -rf /etc/nginx/conf.d/constant.js
  ln -s /opt/constant.js /etc/nginx/conf.d/constant.js
fi

# SSL开启
if [ "${SSL}" = "true" ]; then
  sed -i 's/#.*include \/etc\/nginx\/conf.d\/includes\/https.conf;/include \/etc\/nginx\/conf.d\/includes\/https.conf;/' /etc/nginx/conf.d/*.conf

  # DOMAIN、SSL变量替换
  mv /check_certificate.sh /check_certificate.sh.bk
  envsubst '${DOMAIN}${SSL}' < /check_certificate.sh.bk > /check_certificate.sh
  ./check_certificate.sh

  # 写入定时任务
  crontab -r
  # 将新的定时任务写入crontab
  echo "${SSL_CRON} ./check_certificate.sh" | crontab -
  # 重启cron服务使修改生效
  service cron restart
else
  sed -i 's/include \/etc\/nginx\/conf.d\/includes\/https\.conf;/#&/g' /etc/nginx/conf.d/*.conf
fi

# 后台启动nginx
nginx -g "daemon off;"