#!/bin/bash
# shellcheck shell=bash
# shellcheck disable=SC2016
# shellcheck disable=SC2154
mkdir -p /var/cache/nginx/emby/image

# 自动更新
if [[ "${AUTO_UPDATE}" = "true" ]];then
  cd /embyExternalUrl && git pull
fi

# 删除原有配置文件
rm -rf /etc/nginx/conf.d /etc/nginx/nginx.conf

# 根据服务获取不同的配置文件
if [ "${SERVER}" = "emby" ]; then
  ln -s /embyExternalUrl/emby2Alist/nginx/conf.d /etc/nginx/conf.d
  ln -s /embyExternalUrl/emby2Alist/nginx/nginx.conf /etc/nginx/nginx.conf
else
  ln -s /embyExternalUrl/plex2Alist/nginx/conf.d /etc/nginx/conf.d
  ln -s /embyExternalUrl/plex2Alist/nginx/nginx.conf /etc/nginx/nginx.conf
fi

if [ "${SSL}" = "true" ]; then
  sed -i 's/#.*include \/etc\/nginx\/conf.d\/includes\/https.conf;/include \/etc\/nginx\/conf.d\/includes\/https.conf;/' /etc/nginx/conf.d/*.conf
  check_certificate
else
  sed -i 's/include \/etc\/nginx\/conf.d\/includes\/https\.conf;/#&/g' /etc/nginx/conf.d/*.conf
fi

# 创建配置文件
cat << EOF > /etc/nginx/conf.d/includes/http.conf
server_name default;
listen ${NGINX_PORT}; ## Listens on port IPv4
listen [::]:${NGINX_PORT}; # Listens on port IPv6
EOF

cat << EOF > /etc/nginx/conf.d/includes/https.conf
server_name default;
## SSL SETTINGS ##
listen [::]:${NGINX_SSL_PORT} ssl; ## Listens on port IPv6 with ssl enabled
listen ${NGINX_SSL_PORT} ssl; ## Listens on port IPv4 with ssl enabled
# listen 8095 quic reuseport; ## http3 enabled
http2 on; ## since nginx 1.25.1, the "listen ... http" directive is deprecated
add_header Alt-Svc 'h3=":$server_port"; ma=86400'; ## http3 enabled
ssl_session_timeout 30m;
ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1;
ssl_certificate      /etc/nginx/conf.d/cert/fullchain.pem;  ## Location of your public PEM file.
ssl_certificate_key  /etc/nginx/conf.d/cert/privkey.key;  ## Location of your private PEM file.
ssl_session_cache shared:SSL:10m;
error_page 497 =307 https://$host:$server_port$request_uri; ## if http and https use same port, Redirects http:// to https://
EOF

# 定义检查证书的函数
check_certificate() {
    # 检查 /opt/ssl 文件是否存在
    if [ -e /opt/ssl ]; then
        
        # 检查证书和私钥文件是否存在
        if [ -e /opt/fullchain.pem ] && [ -e /opt/privkey.key ]; then
            
            # 获取当前日期和时间
            current_date=$(date +%s)
            
            # 提取证书的到期日期，并将其转换为 Unix 时间戳
            expiry_date=$(openssl x509 -enddate -noout -in /opt/fullchain.pem | cut -d= -f2 | xargs -I {} date -d "{}" +%s)
            
            # 计算证书到期的天数
            days_until_expiry=$(( (expiry_date - current_date) / 86400 ))
            
            # 判断证书是否在 30 天内到期
            if [ $days_until_expiry -le 30 ]; then
                echo "证书将在 $days_until_expiry 天内到期，执行域名更新脚本"
                bash /opt/ssl

                # 检查证书是否被 Let's Encrypt 成功签发
                if ls /.lego/certificates | grep "${DOMAIN}"; then
                    echo '证书签发成功'
                    # 将证书复制到特定目录
                    mkdir -p /root/.cert
                    cp /.lego/certificates/"${DOMAIN}".crt /opt/fullchain.pem
                    cp /.lego/certificates/"${DOMAIN}".key /opt/privkey.key
                    # 软连接配置文件
                    rm -rf /etc/nginx/conf.d/constant.js
                    mkdir -p /etc/nginx/conf.d/cert/
                    ln -s /opt/constant.js /etc/nginx/conf.d/constant.js
                    ln -s /opt/fullchain.pem /etc/nginx/conf.d/cert/fullchain.pem
                    ln -s /opt/privkey.key /etc/nginx/conf.d/cert/privkey.key
                    nginx -s reload
                else
                    echo '证书签发失败'
                fi
            else
                echo "证书还在有效期"
            fi
        else
            bash /opt/ssl
        fi
    else
        echo "SSL脚本不存在。"
    fi
}

# 后台启动nginx
nginx -g "daemon off;"
